package View;

import Control.TipoPessoa;
import Control.CPF;
import Model.Gerente;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.sql.ResultSet;

/**
 *
 * @author caio
 */
public class TelaPesquisaPessoa extends javax.swing.JFrame {

    private TipoPessoa tipoPessoa = TipoPessoa.CLIENTE;

    public TelaPesquisaPessoa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botPesquisar = new javax.swing.JButton();
        botExcluirItem = new javax.swing.JButton();
        botCadastrarNovoItem = new javax.swing.JButton();
        caixaPesquisaUsuario = new javax.swing.JTextField();
        comboBoxTipoPessoa = new javax.swing.JComboBox<>();
        botEditarItem1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(500, 300));

        botPesquisar.setText("Pesquisar");
        botPesquisar.setPreferredSize(new java.awt.Dimension(88, 25));
        botPesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botPesquisarMouseClicked(evt);
            }
        });
        botPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botPesquisarActionPerformed(evt);
            }
        });
        botPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                botPesquisarKeyPressed(evt);
            }
        });

        botExcluirItem.setText("Excluir");
        botExcluirItem.setPreferredSize(new java.awt.Dimension(88, 25));
        botExcluirItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botExcluirItemMouseClicked(evt);
            }
        });
        botExcluirItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botExcluirItemActionPerformed(evt);
            }
        });

        botCadastrarNovoItem.setText("Cadastrar");
        botCadastrarNovoItem.setPreferredSize(new java.awt.Dimension(88, 25));
        botCadastrarNovoItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botCadastrarNovoItemNovoItemMouseClicked(evt);
            }
        });
        botCadastrarNovoItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botCadastrarNovoItemActionPerformed(evt);
            }
        });
        botCadastrarNovoItem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                botCadastrarNovoItemKeyPressed(evt);
            }
        });

        caixaPesquisaUsuario.setFont(new java.awt.Font("Liberation Sans", 2, 13)); // NOI18N
        caixaPesquisaUsuario.setText("Digite o CPF...");
        caixaPesquisaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixaPesquisaUsuarioActionPerformed(evt);
            }
        });

        comboBoxTipoPessoa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cliente", "Gerente" }));
        comboBoxTipoPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxTipoPessoaActionPerformed(evt);
            }
        });

        botEditarItem1.setText("Editar");
        botEditarItem1.setPreferredSize(new java.awt.Dimension(88, 25));
        botEditarItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botEditarItem1MouseClicked(evt);
            }
        });
        botEditarItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botEditarItem1ActionPerformed(evt);
            }
        });
        botEditarItem1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                botEditarItem1KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(botCadastrarNovoItem, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botEditarItem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botExcluirItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(caixaPesquisaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboBoxTipoPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caixaPesquisaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxTipoPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botExcluirItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botCadastrarNovoItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botEditarItem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botPesquisarActionPerformed
        pesquisar();
    }//GEN-LAST:event_botPesquisarActionPerformed

    private void botCadastrarNovoItemNovoItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botCadastrarNovoItemNovoItemMouseClicked
        chamarTelaCadastro();
    }//GEN-LAST:event_botCadastrarNovoItemNovoItemMouseClicked

    private void comboBoxTipoPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxTipoPessoaActionPerformed
        String itemSelecionado = (String) comboBoxTipoPessoa.getSelectedItem();

        if (itemSelecionado.equals("Cliente")) {
            this.tipoPessoa = TipoPessoa.CLIENTE;
        } else if (itemSelecionado.equals("Gerente")) {
            this.tipoPessoa = TipoPessoa.GERENTE;
        }
    }//GEN-LAST:event_comboBoxTipoPessoaActionPerformed

    private void botCadastrarNovoItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botCadastrarNovoItemActionPerformed
        chamarTelaCadastro();
    }//GEN-LAST:event_botCadastrarNovoItemActionPerformed

    private void caixaPesquisaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixaPesquisaUsuarioActionPerformed
        pesquisar();
    }//GEN-LAST:event_caixaPesquisaUsuarioActionPerformed

    private void botExcluirItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botExcluirItemActionPerformed
        excluir();
    }//GEN-LAST:event_botExcluirItemActionPerformed

    private void botExcluirItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botExcluirItemMouseClicked
        excluir();
    }//GEN-LAST:event_botExcluirItemMouseClicked

    private void botPesquisarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botPesquisarMouseClicked
        pesquisar();
    }//GEN-LAST:event_botPesquisarMouseClicked

    private void botCadastrarNovoItemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botCadastrarNovoItemKeyPressed
        chamarTelaCadastro();
    }//GEN-LAST:event_botCadastrarNovoItemKeyPressed

    private void botEditarItem1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botEditarItem1MouseClicked
        chamarTelaEditarDados();
    }//GEN-LAST:event_botEditarItem1MouseClicked

    private void botEditarItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botEditarItem1ActionPerformed
        chamarTelaEditarDados();
    }//GEN-LAST:event_botEditarItem1ActionPerformed

    private void botPesquisarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botPesquisarKeyPressed
        pesquisar();
    }//GEN-LAST:event_botPesquisarKeyPressed

    private void botEditarItem1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botEditarItem1KeyPressed
        chamarTelaEditarDados();
    }//GEN-LAST:event_botEditarItem1KeyPressed

    /* public void pesquisar() {
        // Recebe o CPF digitado na caixa de pesquisa
        String cpf = caixaPesquisaUsuario.getText();

        if (!validarCPFPesquisado(cpf)) {
        } else {

            if (this.tipoPessoa.equals(TipoPessoa.CLIENTE)) {
                pesquisarTblCliente(cpf);
            } else if (this.tipoPessoa.equals(TipoPessoa.GERENTE)) {
                pesquisarTblGerente(cpf);
            }

        }
    }*/
    private void pesquisar() {
        String cpf = caixaPesquisaUsuario.getText();
        CPF validador = new CPF();
        boolean validarCPF = validador.getValidarCPF(cpf);
        if (true == validarCPF) {
            Gerente pesquisa = new Gerente(null, null, null, null, null, null, null, null);
            ResultSet resultado = pesquisa.getPesquisarCliente(cpf);
            try {
                if (resultado.next()) {
                    String nome = resultado.getString("nome");
                    String cpfBD = resultado.getString("cpf");
                    int idade = resultado.getInt("idade");
                    int idCliente = resultado.getInt("idCliente");
                    int idConta = resultado.getInt("idConta");
                    double saldoAtual = resultado.getDouble("saldoAtual");
                    int statusConta = resultado.getInt("statusCliente");
                    String statusContaStr = statusConta == 1 ? "Ativo" : "Inativo";

                    String mensagem = "Nome: " + nome + "\n"
                            + "CPF: " + cpfBD + "\n"
                            + "Idade: " + idade + "\n"
                            + "ID Cliente: " + idCliente + "\n"
                            + "ID Conta: " + idConta + "\n"
                            + "Saldo Atual: " + saldoAtual + "\n"
                            + "Status da Conta: " + statusContaStr;

                    JOptionPane.showMessageDialog(null, mensagem, "Dados do Cliente", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(null, "Cliente não encontrado", "Erro", JOptionPane.ERROR_MESSAGE);
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Erro ao buscar dados do cliente", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "CPF inválido! Por favor, digite novamente.", "Validador de CPF", JOptionPane.ERROR_MESSAGE);
        }
    }

    /*private void pesquisarTblGerente(String cpf) {
        if (!validarCPFPesquisado(cpf)) {
        } else {
            Gerente pesquisa = new Gerente(null, null, null, null, null, null, null, null);
            ResultSet resultado = pesquisa.getPesquisarGerente(cpf);
            try {
                if (resultado.next()) {
                    String nome = resultado.getString("nome");
                    String cpfBD = resultado.getString("cpf");
                    int idade = resultado.getInt("idade");
                    int idGerente = resultado.getInt("idGerente");

                    String mensagem = "Nome: " + nome + "\n"
                            + "CPF: " + cpfBD + "\n"
                            + "Idade: " + idade + "\n"
                            + "ID Gerente: " + idGerente;

                    JOptionPane.showMessageDialog(null, mensagem, "Dados do Gerente", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(null, "Gerente não encontrado", "Erro", JOptionPane.ERROR_MESSAGE);
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Erro ao buscar dados do gerente", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
    }*/
    private void chamarTelaCadastro() {
        TipoPessoa pessoa = null;

        // Pergunta quem quer cadastrar
        int opçao = JOptionPane.showConfirmDialog(null,
                "Deseja cadastrar um cliente ou gerente?",
                "Selecionar tipo de cadastro",
                JOptionPane.YES_NO_OPTION);

        switch (opçao) {
            case JOptionPane.YES_OPTION -> {
                // Cadastrar cliente
                pessoa = TipoPessoa.CLIENTE;
            }

            case JOptionPane.NO_OPTION -> {
                // Cadastrar gerente
                pessoa = TipoPessoa.GERENTE;
            }

            default ->
                throw new AssertionError();
        }

        this.dispose();

        if (pessoa.equals(TipoPessoa.CLIENTE)) {
            new TelaCadastroCliente(pessoa).setVisible(true);
        } else if (pessoa.equals(TipoPessoa.GERENTE)) {
            new TelaCadastroGerente(pessoa).setVisible(true);
        }
    }

    private void chamarTelaEditarDados() {
        boolean auxiliar = false;
        String cpf = caixaPesquisaUsuario.getText();

        // Pergunta quem quer cadastrar
        int opçao = JOptionPane.showConfirmDialog(null,
                "Deseja editar esse cliente?",
                "Selecionar tipo de cadastro",
                JOptionPane.YES_NO_OPTION);

        switch (opçao) {
            case JOptionPane.YES_OPTION -> {
                auxiliar = true;
            }

            case JOptionPane.NO_OPTION -> {
                auxiliar = false;
            }

            default ->
                throw new AssertionError();
        }

        if (auxiliar == true) {
            this.dispose();
            new TelaEditar(cpf).setVisible(true);
        }
    }

    private void excluir() {
        int opçao = JOptionPane.showConfirmDialog(null, "Realmente deseja excluir esse usuário?", "Excluir usuário", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

        switch (opçao) {
            case JOptionPane.YES_OPTION -> {
                String cpf = caixaPesquisaUsuario.getText();
                Gerente ger = new Gerente(null, null, null, null, null, null, null, null);
                ger.getExcluirCliente(cpf);
            }

            case JOptionPane.NO_OPTION -> {
                //Não excluir
            }

            default ->
                throw new AssertionError();
        }
    }

    /* private boolean validarCPFPesquisado(String cpf) {
        CPF validador = new CPF();
        boolean validarCPF = validador.getValidarCPF(cpf);

        boolean valido = validarCPF;

        if (!validarCPF) {
            JOptionPane.showMessageDialog(null, "CPF inválido! Por favor, digite novamente.", "Validador de CPF", JOptionPane.ERROR_MESSAGE);
            valido = false;
        } else {
            valido = true;
        }

        return valido;
    }*/
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            new TelaPesquisaPessoa().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botCadastrarNovoItem;
    private javax.swing.JButton botEditarItem1;
    private javax.swing.JButton botExcluirItem;
    private javax.swing.JButton botPesquisar;
    private javax.swing.JTextField caixaPesquisaUsuario;
    private javax.swing.JComboBox<String> comboBoxTipoPessoa;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
